import BlogShell from './blog-shell';

export const metadata = {
  title: 'Fence Business Software Blog | FenceBossPro',
  description: 'Guides on fence estimating, scheduling, crew dispatch, invoicing, installation, and running a fence company with software.',
};

const silo0 = [
  { title: 'Card-on-File Payments: How Fencing Software Speeds Up Getting Paid for Fence Work', description: 'How card-on-file payments in fencing software let you collect deposits and final balances on fence jobs in seconds instead of chasing checks for weeks.', href: '/blogs/card-on-file-payments-fencing-software' },
  { title: 'Estimate Templates for Chain Link, Vinyl, Wood &amp; Aluminum Fence in Fencing Software', description: 'How fencing software uses material-specific estimate templates to bid chain link, vinyl, wood, and aluminum fence projects faster and more accurately by the linear foot.', href: '/blogs/chain-link-vinyl-wood-aluminum-estimate-templates-fencing-software' },
  { title: 'Client &amp; Property Profiles: How Fencing Software Remembers Every Yard You&apos;ve Fenced', description: 'How fencing software stores client and property profiles so you remember fence types, post counts, gate hardware, and bid history for every yard.', href: '/blogs/client-property-profiles-fencing-software' },
  { title: 'Crew Dispatch &amp; Routing: How Fencing Software Gets Fence Installers to the Right Job', description: 'See how fencing software dispatches and routes fence install crews to the right job with materials, gates, and linear-foot details already loaded.', href: '/blogs/crew-dispatch-routing-fencing-software' },
  { title: 'Handling Change Orders &amp; Fence-Line Adjustments With Fencing Software', description: 'See how fencing software handles change orders and fence-line adjustments &mdash; re-quoting materials, re-billing, and keeping every fence job profitable.', href: '/blogs/fencing-software-change-orders-fence-line-adjustments' },
  { title: 'Commercial vs. Residential Fence Jobs: Running Both in Fencing Software', description: 'See how fencing software handles commercial and residential fence jobs side by side&mdash;bids, materials, scheduling, progress billing, and crew dispatch.', href: '/blogs/fencing-software-commercial-vs-residential-fence-jobs' },
  { title: 'Fencing Software: The Complete Guide for Fence Installation &amp; Repair Companies', description: 'See how fencing software handles linear-foot takeoffs, material lists, line-item bids, scheduling, dispatch, and card-on-file invoicing for fence pros.', href: '/blogs/fencing-software-complete-guide' },
  { title: 'Counting Posts, Concrete &amp; Footings: Accurate Takeoffs With Fencing Software', description: 'How fencing software turns linear-foot measurements into accurate post counts, concrete bags, and footing quantities so your bids stop bleeding margin on every job.', href: '/blogs/fencing-software-concrete-footings-post-counts-takeoffs' },
  { title: 'How Fencing Software Improves the Customer Experience From Quote to Final Walkthrough', description: 'See how fencing software gives homeowners a smoother experience with clear bids, scheduling texts, card-on-file payments, and an organized final walkthrough.', href: '/blogs/fencing-software-customer-experience-from-quote-to-final-walk' },
  { title: 'Customer Texts in Fencing Software: Keeping Fence Clients Updated From Quote to Final Walk', description: 'See how customer texts in fencing software keep fence clients updated from quote to final walk, cutting callbacks on every install and repair job.', href: '/blogs/fencing-software-customer-texts-keep-fence-clients-updated' },
  { title: 'A Day in the Life: The Daily Fencing Software Workflow of a Fence Business Owner', description: 'Walk through a fence business owner\'s day in fencing software, from morning dispatch and line-item bids to materials, customer texts, and card payments.', href: '/blogs/fencing-software-daily-workflow-fence-business-owner' },
  { title: 'Deposits &amp; Progress Billing for Fence Jobs With Fencing Software', description: 'See how fencing software handles deposits, progress billing, and card-on-file payments so fence crews get paid on time for every phase of the job.', href: '/blogs/fencing-software-deposits-progress-billing-fence-jobs' },
  { title: 'Managing Fence Repair &amp; Gate Service Calls With Fencing Software', description: 'See how fencing software handles fence repair and gate service calls&mdash;fast estimates, parts tracking, dispatch, and card-on-file payments in one place.', href: '/blogs/fencing-software-fence-repair-gate-service-calls' },
  { title: 'Following Up on Fence Leads: How Fencing Software Keeps Your Pipeline Full', description: 'Fencing software that tracks every fence lead, automates follow-up texts, and turns line-item estimates into booked installs so your pipeline never goes cold.', href: '/blogs/fencing-software-follow-up-fence-leads-pipeline' },
  { title: 'Quoting Gates, Hardware &amp; Add-Ons in Your Fence Estimates With Fencing Software', description: 'See how fencing software builds gates, hardware, and add-ons into line-item fence estimates so every post, hinge, and latch is priced and billed.', href: '/blogs/fencing-software-gate-hardware-add-ons-estimates' },
  { title: 'Presenting Good-Better-Best Fence Quote Options With Fencing Software', description: 'See how fencing software builds good-better-best fence quote options &mdash; tiered materials, gates, and pricing &mdash; so customers pick a package and you close more bids.', href: '/blogs/fencing-software-good-better-best-fence-quote-options' },
  { title: 'Invoicing Fence Customers Faster: A Look at Billing in Fencing Software', description: 'See how fencing software turns line-item estimates into invoices, captures deposits and progress billing, and gets fence jobs paid faster.', href: '/blogs/fencing-software-invoicing-fence-customers-faster' },
  { title: 'Using the Job Board in Fencing Software to Keep Every Fence Project Moving', description: 'See how the Job Board in FenceBossPro tracks every fence project from signed estimate to final payment so no job stalls between material order and install.', href: '/blogs/fencing-software-job-board-keep-every-fence-project-moving' },
  { title: 'How Fencing Software Builds Line-Item Estimates That Win More Fence Bids', description: 'See how fencing software turns linear-foot takeoffs and material lists into clear line-item estimates that win more fence bids and protect your margins.', href: '/blogs/fencing-software-line-item-estimates-that-win-bids' },
  { title: 'Protecting Your Margins: Material Costs &amp; Fence Pricing in Fencing Software', description: 'See how fencing software ties material costs, linear-foot takeoffs, and gate hardware to your bids so every fence job protects the margin you priced.', href: '/blogs/fencing-software-material-cost-margins-fence-pricing' },
  { title: 'Tracking Posts, Panels, Pickets &amp; Rails: Materials Management in Fencing Software', description: 'See how FenceBossPro tracks posts, panels, pickets, rails, concrete, gates and hardware on every fence job so estimates, orders and invoices stay tight.', href: '/blogs/fencing-software-materials-parts-tracking-posts-panels-pickets' },
  { title: 'Estimating &amp; Managing Ornamental Aluminum Fence Projects in Fencing Software', description: 'How fencing software builds accurate ornamental aluminum fence estimates, tracks panels, posts, and gates, schedules crews, and bills deposits and progress payments.', href: '/blogs/fencing-software-ornamental-aluminum-fence-projects' },
  { title: 'Project Scheduling for Multi-Day Fence Builds in Fencing Software', description: 'See how FenceBossPro project scheduling keeps multi-day wood, vinyl, and chain link fence builds on track with phased jobs, crew dispatch, and material timing.', href: '/blogs/fencing-software-project-scheduling-multi-day-fence-builds' },
  { title: 'From Estimate to Purchase Order: Ordering Fence Materials With Fencing Software', description: 'See how fencing software turns a line-item fence estimate into an accurate purchase order so you order the right posts, panels, and hardware every time.', href: '/blogs/fencing-software-purchase-orders-supplier-ordering' },
  { title: 'The ROI of Fencing Software: What Fence Companies Actually Save', description: 'See the real ROI of fencing software: faster line-item bids, tighter material takeoffs, fewer missed payments, and crews that stay on schedule all season.', href: '/blogs/fencing-software-roi-what-fence-companies-save' },
  { title: 'Scaling From One Fence Crew to Several Without Chaos Using Fencing Software', description: 'See how fencing software keeps estimates, materials, scheduling, dispatch, and invoicing organized as you grow from one fence crew to several.', href: '/blogs/fencing-software-scaling-from-one-crew-to-several' },
  { title: 'Fencing Software vs. Spreadsheets: Why Manual Fence Bidding Costs You Money', description: 'Manual fence bids leak profit through math errors and missed materials. See how FenceBossPro software turns linear-foot takeoffs into accurate, fast bids.', href: '/blogs/fencing-software-vs-spreadsheets-manual-bidding' },
  { title: 'Getting Started With Fencing Software: A First-Week Setup Plan for Fence Crews', description: 'A practical first-week setup plan for fence crews: load materials, build your estimate templates, schedule jobs, and turn on customer texts in FenceBossPro.', href: '/blogs/getting-started-fencing-software-first-week-setup' },
  { title: 'Linear-Foot Takeoffs Made Simple With Fencing Software', description: 'See how FenceBossPro turns linear-foot takeoffs into accurate posts, panels, and gate material lists so your fence bids are fast, priced right, and profitable.', href: '/blogs/linear-foot-takeoffs-fencing-software' },
  { title: 'Scheduling Fence Installs Around Material Delivery With Fencing Software', description: 'Sync fence install dates to your material deliveries with fencing software that links takeoffs, parts, the job board, and crew dispatch in one place.', href: '/blogs/scheduling-fence-installs-around-material-delivery-fencing-software' },
];

const silo1 = [
  { title: 'Quoting Aluminum and Ornamental Fence Without Missing a Bracket', description: 'See how FenceBossPro builds aluminum and ornamental fence estimates with every panel, post, bracket, and gate counted from a linear-foot takeoff.', href: '/blogs/aluminum-ornamental-fence-estimating-software' },
  { title: 'How to Build Your First Fence Estimate in FenceBossPro, Line by Line', description: 'A step-by-step walkthrough of building your first line-item fence estimate in FenceBossPro, from linear-foot takeoff to materials, gates, and a sent quote.', href: '/blogs/build-first-fence-estimate-fencebosspro' },
  { title: 'Chain Link Fence Estimates: Terminal Posts, Line Posts, and Fabric in One Bid', description: 'See how fencing software builds chain link estimates with terminal posts, line posts, fabric, and hardware itemized in one clean, accurate bid.', href: '/blogs/chain-link-fence-estimate-terminal-posts-fabric' },
  { title: 'Collecting a Deposit With Card-on-File Right From the Fence Estimate', description: 'See how FenceBossPro lets a fence customer approve a bid, leave a card on file, and pay a deposit in one tap &mdash; right from the estimate.', href: '/blogs/collect-fence-deposit-card-on-file-estimate' },
  { title: 'Baking Concrete, Fasteners, and Hardware Into Your Fence Estimates', description: 'See how FenceBossPro folds concrete, fasteners, and gate hardware into every fence estimate automatically so your bids stop leaking profit on the small stuff.', href: '/blogs/concrete-and-hardware-fence-estimate-costs' },
  { title: 'Turning a Fence Estimate Into an Invoice and Taking Card Payments', description: 'Convert a line-item fence bid into an invoice in one click, bill deposits and progress draws, and take card-on-file payments without re-keying anything.', href: '/blogs/fence-estimate-invoicing-card-payments' },
  { title: 'Good-Better-Best Fence Estimates: Offering Options Without Rebuilding the Bid', description: 'See how FenceBossPro lets fence contractors build good-better-best estimate options from one takeoff &mdash; swap materials, save tiers, and close more bids.', href: '/blogs/fence-estimate-revisions-options-good-better-best' },
  { title: 'From Approved Fence Estimate to a Job on the Board in One Click', description: 'See how FenceBossPro turns an approved line-item fence estimate into a scheduled job on the board, with materials, deposit, and crew dispatch attached.', href: '/blogs/fence-estimate-to-scheduled-job-board' },
  { title: 'Deposits and Progress Billing: Getting Paid Across a Multi-Day Fence Job', description: 'How FenceBossPro uses deposits, progress billing, and card-on-file payments to keep cash flowing through long, material-heavy multi-day fence installs.', href: '/blogs/fence-estimating-software-deposits-progress-billing' },
  { title: 'From Bid to Dispatch: Routing Crews to Approved Fence Jobs', description: 'See how FenceBossPro turns an approved fence bid into a scheduled, dispatched, routed job so crews show up with the right materials and posts.', href: '/blogs/fence-estimating-software-dispatch-routing-bids' },
  { title: 'How Fence Estimating Software Protects Your Margin on Every Bid', description: 'See how FenceBossPro fence estimating software builds linear-foot takeoffs, prices materials, and locks in margin so no bid leaves money on the table.', href: '/blogs/fence-estimating-software-protect-profit-margins' },
  { title: 'The ROI of Fence Estimating Software for a Growing Install Crew', description: 'See how fence estimating software pays for itself by speeding up line-item bids, tightening material takeoffs, and turning more quotes into signed jobs.', href: '/blogs/fence-estimating-software-roi-for-installers' },
  { title: 'Fence Estimating Software vs. Spreadsheets: Why Bids Should Live in FenceBossPro', description: 'See why fence contractors ditch spreadsheets for FenceBossPro estimating: linear-foot takeoffs, materials, deposits, and bids that turn into scheduled jobs.', href: '/blogs/fence-estimating-software-vs-spreadsheets' },
  { title: 'Attaching a Materials &amp; Parts List to Every Fence Estimate', description: 'FenceBossPro builds a materials and parts list into every fence estimate&mdash;posts, panels, rails, concrete, gates, and hardware priced from a linear-foot takeoff.', href: '/blogs/fence-materials-parts-list-estimating-software' },
  { title: 'Estimating Fence Repairs vs. Full Installs in the Same System', description: 'See how fencing software estimates quick fence repairs and full installs in one place, with line-item bids, materials, deposits, and scheduling that fit both.', href: '/blogs/fence-repair-estimates-vs-new-install-bids' },
  { title: 'Adding Gates and Gate Hardware to a Fence Estimate the Right Way', description: 'See how FenceBossPro adds gates, posts, hinges, latches, and gate hardware as priced line items so your fence estimates stop leaking profit on every job.', href: '/blogs/gate-pricing-fence-estimates-hardware' },
  { title: 'Line-Item Fence Bids: Breaking a Job Into Posts, Panels, and Pickets', description: 'See how FenceBossPro breaks fence jobs into line-item bids &mdash; posts, panels, pickets, rails, concrete, and gates &mdash; so estimates are accurate and profitable.', href: '/blogs/line-item-fence-bids-posts-panels-pickets' },
  { title: 'Linear-Foot Takeoffs Made Fast: Pricing Fence Runs by the Foot in FenceBossPro', description: 'Price fence runs by the linear foot in FenceBossPro. Build fast takeoffs, auto-calc posts, panels, and concrete, and turn footage into winning line-item bids.', href: '/blogs/linear-foot-takeoffs-fence-estimating-software' },
  { title: 'Building On-Site Fence Estimates From the Truck Before You Leave the Driveway', description: 'Build line-item fence estimates on-site with FenceBossPro&mdash;linear-foot takeoffs, posts, panels, gates, and hardware priced and sent before you pull away.', href: '/blogs/on-site-fence-estimates-from-the-truck' },
  { title: 'Saved Line Items and Price Lists: Quote Fences in Minutes, Not Hours', description: 'See how FenceBossPro saved line items and reusable price lists turn fence estimates into a few clicks &mdash; accurate bids for posts, panels, gates, and labor in minutes.', href: '/blogs/price-fence-estimates-faster-saved-line-items' },
  { title: 'Professional Fence Quotes That Win More Jobs Than a Napkin Number', description: 'See how fence estimating software turns linear-foot takeoffs and material lists into professional quotes that win more fence jobs than a scribbled napkin number.', href: '/blogs/professional-fence-quotes-win-more-jobs' },
  { title: 'Client and Property Profiles That Speed Up Every Repeat Fence Estimate', description: 'See how FenceBossPro client and property profiles store past bids, materials, and layouts so every repeat fence estimate goes out in minutes, not hours.', href: '/blogs/property-profiles-faster-fence-estimates' },
  { title: 'Cutting Estimate Errors With Standardized Fence Pricing for the Whole Team', description: 'See how FenceBossPro standardizes fence pricing across your team so every estimator bids posts, panels, gates, and labor the same way &mdash; with fewer costly errors.', href: '/blogs/reduce-fence-estimate-errors-standardized-pricing' },
  { title: 'Scaling to Multiple Fence Crews With One Consistent Estimating Process', description: 'See how a consistent estimating process in fencing software lets you scale to multiple fence crews without bids, pricing, or margins falling apart.', href: '/blogs/scale-fence-crews-consistent-estimating' },
  { title: 'Stop Underbidding Fence Jobs: Let the Software Catch Hidden Material Costs', description: 'FenceBossPro builds line-item fence bids from your linear-foot takeoff so posts, panels, concrete, gates, and hardware are never left off the estimate.', href: '/blogs/stop-underbidding-fence-jobs-material-costs' },
  { title: 'Texting Fence Estimates to Customers for Same-Day Approvals', description: 'Text line-item fence estimates straight to your customer&apos;s phone in FenceBossPro and win same-day approvals instead of waiting on emailed PDFs.', href: '/blogs/text-fence-estimates-to-customers-faster-approvals' },
  { title: 'Tracking Your Fence Estimate Pipeline and Following Up on Open Bids', description: 'See how FenceBossPro tracks every open fence bid in one pipeline, automates follow-up texts, and turns stale estimates into signed jobs and deposits.', href: '/blogs/track-fence-estimate-pipeline-follow-ups' },
  { title: 'Estimating Vinyl Fence by the Section Instead of Guessing', description: 'See how FenceBossPro builds vinyl fence bids by the panel section&mdash;posts, panels, caps, and gates priced automatically from your linear-foot takeoff.', href: '/blogs/vinyl-fence-estimating-software-panel-sections' },
  { title: 'Why Fence Businesses Switch From Generic Tools to FenceBossPro Estimating', description: 'See why fence contractors drop spreadsheets and generic estimating apps for FenceBossPro line-item bids, linear-foot takeoffs, and materials lists.', href: '/blogs/why-fence-businesses-switch-to-fencebosspro-estimating' },
  { title: 'A Reusable Wood Fence Estimate Template That Prices Itself', description: 'Build a reusable wood fence estimate template in FenceBossPro that prices line items, materials, and labor automatically from your linear-foot takeoff.', href: '/blogs/wood-fence-estimate-template-fencebosspro' },
];

const silo2 = [
  { title: 'How to Stop Double-Booking Fence Crews When Estimates and Installs Collide', description: 'FenceBossPro keeps estimates and installs on one shared schedule so a fence crew is never booked for two jobs at once&mdash;no overlaps, no driving twice.', href: '/blogs/avoid-double-booking-fence-crews' },
  { title: 'Managing a Fence Install Backlog: A Waiting List That Books Itself', description: 'Turn your fence install backlog into a self-booking waiting list. FenceBossPro fills cancellations and open days from approved, deposit-paid jobs automatically.', href: '/blogs/backlog-waiting-list-fence-installs' },
  { title: 'Client &amp; Property Profiles: Scheduling the Right Fence Crew With the Right History', description: 'How client and property profiles in FenceBossPro let you schedule the right fence crew, with the full job history, materials, and site notes already attached.', href: '/blogs/client-property-profiles-fence-scheduling' },
  { title: 'Automatic Customer Texts for Fence Install Day: Reminders That Cut No-Shows', description: 'See how automatic install-day text reminders in fence scheduling software cut homeowner no-shows, dead trips, and reschedules on every fence job.', href: '/blogs/customer-text-reminders-fence-install-day' },
  { title: 'Turning a Signed Fence Estimate Into a Scheduled Job in One Tap', description: 'See how FenceBossPro turns a signed fence estimate into a scheduled job in one tap, carrying materials, deposit, crew dispatch, and customer texts along.', href: '/blogs/estimate-to-scheduled-fence-job' },
  { title: 'Collect the Deposit, Then Schedule: Tying Fence Job Dates to Card-on-File Deposits', description: 'See how FenceBossPro ties fence job dates to card-on-file deposits so crews only get scheduled after the money lands.', href: '/blogs/fence-job-deposits-schedule-around-payment' },
  { title: 'Five Fence Scheduling Mistakes That Quietly Cost You Jobs', description: 'Five fence scheduling mistakes that quietly cost you jobs, and how FenceBossPro ties materials, crews, dispatch, and customer texts to one live Job Board.', href: '/blogs/fence-scheduling-mistakes-cost-money' },
  { title: 'Fence Scheduling Software vs. the Whiteboard: Why Fence Crews Outgrow Paper Calendars', description: 'Why fence crews outgrow whiteboards and paper calendars, and how FenceBossPro scheduling software ties jobs, materials, crews, and customer texts together.', href: '/blogs/fence-scheduling-software-vs-paper-calendar' },
  { title: 'Scheduling Gate Installs &amp; Hardware Jobs as Separate Line-Item Visits', description: 'See how FenceBossPro schedules gate installs and hardware swaps as their own line-item visits so short jobs get tracked, dispatched, and invoiced right.', href: '/blogs/gate-installation-scheduling-software' },
  { title: 'How the Job Board Runs Your Fence Company\'s Daily Schedule', description: 'See how the FenceBossPro job board turns estimates into a dispatched daily schedule, routing crews to fence installs, repairs, and gate jobs with ease.', href: '/blogs/job-board-fence-business-daily-scheduling' },
  { title: 'Know Each Day\'s Fence Job Revenue Before You Dispatch the Crew', description: 'See how FenceBossPro shows each day\'s booked fence job revenue before dispatch, so you load crews with profitable installs, repairs, and gate work.', href: '/blogs/know-fence-crew-revenue-before-dispatch' },
  { title: 'How Linear-Foot Takeoffs Tell You How Long a Fence Job Really Takes to Schedule', description: 'See how FenceBossPro turns linear-foot takeoffs into accurate crew-day estimates so you schedule fence jobs by real duration, not a guess on the calendar.', href: '/blogs/linear-foot-takeoff-feeds-fence-schedule' },
  { title: 'When Posts or Panels Are Backordered: Rescheduling Fence Jobs the Smart Way', description: 'See how FenceBossPro reschedules backordered fence jobs in one move, slotting ready jobs into open days so a material shortage never wastes a crew.', href: '/blogs/material-shortage-reschedule-fence-jobs' },
  { title: 'Loading the Trailer Right: How a Job\'s Materials List Makes the Schedule Ready', description: 'See how FenceBossPro turns each fence job&apos;s line-item materials list into a load-ready schedule so crews roll out with every post, panel, and gate.', href: '/blogs/materials-list-fence-job-schedule-ready' },
  { title: 'Run Fence Job Scheduling Without a Full-Time Office Manager', description: 'See how FenceBossPro lets a small fence crew schedule installs, dispatch jobs, and bill clients without paying for a full-time office manager.', href: '/blogs/office-manager-free-fence-scheduling' },
  { title: 'Progress Billing Multi-Day Fence Jobs as Each Phase Is Scheduled and Done', description: 'How FenceBossPro ties progress billing to your fence schedule, releasing each draw as a phase is dispatched and completed so cash matches the work.', href: '/blogs/progress-billing-fence-jobs-by-phase' },
  { title: 'How Fence Scheduling Software Cuts Your Office Scheduling Time in Half', description: 'Where fence scheduling software cuts office time in half — from the Job Board and crew dispatch to deposit invoicing and automatic customer texts on every install.', href: '/blogs/reduce-scheduling-time-fence-company' },
  { title: 'Rescheduling a Fence Job From the Truck in One Tap', description: 'Learn how FenceBossPro lets fence crews reschedule an install or repair from the truck in one tap, with auto customer texts and a live Job Board.', href: '/blogs/reschedule-fence-job-one-tap-mobile' },
  { title: 'The ROI of Fence Scheduling Software: How Tighter Days Pay for the Subscription', description: 'See how FenceBossPro fence scheduling software pays for itself by tightening crew days, cutting drive time, and turning every booked job into invoiced revenue.', href: '/blogs/roi-fence-scheduling-software-pays-for-itself' },
  { title: 'Scaling From One Fence Crew to Four Without Losing the Schedule', description: 'Learn how FenceBossPro scheduling software lets fence companies add crews, dispatch jobs, and keep installs, repairs, and gates on track as you grow.', href: '/blogs/scale-fence-crews-multiple-job-schedule' },
  { title: 'Scheduling Fence Jobs Around Post, Panel &amp; Concrete Delivery Dates', description: 'See how FenceBossPro ties fence job scheduling to post, panel, and concrete delivery dates so crews never show up before the materials do.', href: '/blogs/schedule-fence-jobs-around-material-delivery' },
  { title: 'Scheduling Wood, Vinyl, Chain Link &amp; Aluminum Jobs by Crew Specialty', description: 'See how FenceBossPro schedules wood, vinyl, chain link and aluminum fence jobs by crew specialty so the right crew, materials and skills land on every job.', href: '/blogs/schedule-fence-jobs-by-material-type' },
  { title: 'Scheduling Fence Repairs and New Installs on the Same Crew Calendar', description: 'See how FenceBossPro schedules quick fence repairs and multi-day new installs on one crew calendar so the Job Board, dispatch, and invoicing all stay in sync.', href: '/blogs/schedule-fence-repair-vs-new-install-jobs' },
  { title: 'Scheduling Utility Locates &amp; Permits Before the Fence Dig Date', description: 'See how FenceBossPro scheduling software locks in utility locates and permit lead times before every fence dig date so crews never break ground early.', href: '/blogs/schedule-permit-locate-before-fence-dig' },
  { title: 'Seasonal Fence Scheduling: Building Routes for the Spring &amp; Fall Install Rush', description: 'See how FenceBossPro scheduling software helps fence companies batch jobs, build tight crew routes, and survive the spring and fall install rush.', href: '/blogs/seasonal-fence-scheduling-busy-season' },
  { title: 'Setting Up Fence Scheduling Software in Your First Week: A Step-by-Step Start', description: 'A first-week setup plan for fence scheduling software: load crews, jobs, and materials into FenceBossPro so your Job Board runs your fencing business by Friday.', href: '/blogs/set-up-fence-scheduling-software-first-week' },
  { title: 'Scheduling Two-Phase Fence Jobs: Set Posts, Let Concrete Cure, Then Hang Panels', description: 'See how FenceBossPro schedules two-phase fence jobs&mdash;set posts, let concrete cure, then hang panels&mdash;with linked visits, crew dispatch, and texts.', href: '/blogs/two-phase-fence-jobs-set-posts-then-panels' },
  { title: 'Handling Weather Delays: Rescheduling Fence Jobs Without Losing the Whole Week', description: 'See how FenceBossPro scheduling software lets fence crews reschedule rained-out jobs, re-dispatch routes, and text customers without losing the week.', href: '/blogs/weather-delays-fence-scheduling-software' },
];

const silo3 = [
  { title: 'Capacity Planning: How Many Fence Jobs Can Your Crews Actually Handle', description: 'FenceBossPro turns linear-foot takeoffs, crew hours, and the Job Board into real capacity numbers so you stop overbooking and underbooking fence crews.', href: '/blogs/capacity-planning-fence-crew-dispatch-software' },
  { title: 'Card-on-File Payments: Closing Out Fence Jobs the Day the Crew Finishes', description: 'See how FenceBossPro card-on-file payments let fence crews close out jobs and collect the balance the same day the last post is set and the gate is hung.', href: '/blogs/card-on-file-payments-fence-crew-dispatch-software' },
  { title: 'Dispatching Chain Link, Vinyl, and Wood Fence Crews From One Board', description: 'See how FenceBossPro dispatches chain link, vinyl, and wood fence crews from one Job Board with routing, materials, and progress billing built in.', href: '/blogs/chain-link-vinyl-wood-crew-dispatch-software' },
  { title: 'How to Choose Fence Crew and Dispatch Software for a Growing Contractor', description: 'A practical buyer&apos;s guide to picking fence crew and dispatch software that handles estimates, materials, scheduling, routing, and payments as you grow.', href: '/blogs/choosing-fence-crew-dispatch-software' },
  { title: 'Client and Property Profiles That Give Fence Crews Everything On Arrival', description: 'See how FenceBossPro client and property profiles hand fence crews gate codes, layouts, materials, and history the moment they roll up to the job.', href: '/blogs/client-property-profiles-fence-crew-dispatch-software' },
  { title: 'Crew Accountability and Time Tracking in Fence Dispatch Software', description: 'See how FenceBossPro tracks fence crew hours, job time, and dispatch status so every post set, panel, and gate gets billed and accounted for.', href: '/blogs/crew-accountability-time-tracking-fence-dispatch-software' },
  { title: 'Crew Routing With Fence Dispatch Software: Fewer Miles, More Posts in the Ground', description: 'See how fence dispatch software builds tight crew routes, cuts windshield time, and keeps installers digging posts instead of driving across town.', href: '/blogs/crew-routing-fence-dispatch-software' },
  { title: 'How Tight Crew Dispatch Improves the Fence Customer Experience', description: 'See how FenceBossPro crew dispatch, scheduling, and automatic customer texts turn fence installs into a smooth, on-time experience clients rave about.', href: '/blogs/customer-experience-fence-crew-dispatch-software' },
  { title: 'Automated Customer Texts That Cut Status Calls During Fence Installs', description: 'How FenceBossPro automated customer texts cut status calls, keep fence install clients informed, and free your crews and office to focus on the build.', href: '/blogs/customer-texts-fence-crew-dispatch-software' },
  { title: 'A Daily Dispatch Routine That Gets Fence Crews Out the Door Faster', description: 'A repeatable morning dispatch routine in FenceBossPro that loads jobs, materials, and routes so your fence crews roll out on time every day.', href: '/blogs/daily-dispatch-routine-fence-crew-software' },
  { title: 'Collecting Deposits and Progress Billing as Fence Crews Hit Milestones', description: 'See how FenceBossPro collects deposits up front and triggers progress billing as fence crews hit milestones&mdash;dig, set posts, hang panels, hang gates.', href: '/blogs/deposits-progress-billing-fence-crew-dispatch-software' },
  { title: 'Fence Crew and Dispatch Software: The Complete Guide for Fence Contractors', description: 'A complete guide to fence crew and dispatch software: schedule installs, route crews, build line-item bids, track materials, and invoice with card on file.', href: '/blogs/fence-crew-dispatch-software-complete-guide' },
  { title: 'Dispatching Gate and Add-On Work Without Derailing the Fence Schedule', description: 'How FenceBossPro slots gate installs, repairs, and add-on work into your fence crew dispatch board without blowing up the linear-foot schedule or your margins.', href: '/blogs/gate-jobs-add-ons-fence-crew-dispatch-software' },
  { title: 'Invoicing From the Field the Moment a Fence Crew Wraps Up', description: 'See how FenceBossPro lets your fence crew build and send the final invoice from the job site the minute the last post is set and the gate swings.', href: '/blogs/invoicing-from-the-field-fence-crew-dispatch-software' },
  { title: 'How the Job Board Keeps Every Fence Crew on Schedule', description: 'See how the FenceBossPro Job Board centralizes fence jobs, dispatch, and crew scheduling so no install, repair, or gate ever slips through the cracks.', href: '/blogs/job-board-fence-crew-dispatch-software' },
  { title: 'Tracking Crew Labor Hours Against the Estimate on Every Fence Job', description: 'See how FenceBossPro tracks fence crew labor hours against the estimated hours on every job so you catch margin leaks before they wreck your season.', href: '/blogs/labor-hours-vs-estimate-fence-crew-dispatch-software' },
  { title: 'Line-Item Fence Estimates That Flow Straight Into Crew Dispatch', description: 'See how FenceBossPro turns line-item fence estimates into crew dispatch &mdash; materials, schedules, and invoices built from one accepted bid.', href: '/blogs/line-item-estimates-fence-crew-dispatch-software' },
  { title: 'Linear-Foot Takeoffs That Drive Accurate Crew Schedules and Material Orders', description: 'See how FenceBossPro turns linear-foot takeoffs into accurate fence bids, right-sized material orders, and crew schedules your dispatcher can trust.', href: '/blogs/linear-foot-takeoffs-fence-crew-dispatch-software' },
  { title: 'Tracking Posts, Panels, and Hardware From Estimate to Crew Assignment', description: 'See how FenceBossPro tracks fence posts, panels, and hardware from the line-item estimate all the way to the crew assignment so nothing gets missed.', href: '/blogs/materials-parts-tracking-fence-crew-dispatch-software' },
  { title: 'The Mobile App That Replaces the Morning Roll Call for Fence Crews', description: 'FenceBossPro pushes each fence crew their full day&mdash;jobs, routes, materials, and gate notes&mdash;straight to the mobile app, so you skip the morning roll call.', href: '/blogs/morning-roll-call-mobile-app-fence-crew-dispatch-software' },
  { title: 'Coordinating Multi-Day Fence Projects Across Several Crews', description: 'FenceBossPro splits multi-day fence projects into scheduled phases across crews, ties each to its materials, and keeps the office, field, and customer in sync.', href: '/blogs/multi-day-fence-projects-crew-dispatch-software' },
  { title: 'Reassigning Fence Crews On the Fly When Plans Change Mid-Day', description: 'See how FenceBossPro lets you reassign fence crews mid-day&mdash;drag job cards, re-dispatch routes, and text customers when a sick call or short delivery hits.', href: '/blogs/reassigning-crews-on-the-fly-fence-dispatch-software' },
  { title: 'Reducing Windshield Time: Smarter Fence Crew Dispatch and Routing', description: 'Cut windshield time with fence crew dispatch software that builds tight routes, stages materials by job, and keeps installers setting posts, not driving.', href: '/blogs/reducing-windshield-time-fence-crew-dispatch-software' },
  { title: 'Slotting Fence Repair and Service Calls Between Big Install Jobs', description: 'See how FenceBossPro slots fence repair and service calls between big install jobs using the Job Board, crew dispatch, and card-on-file invoicing.', href: '/blogs/repair-service-calls-fence-crew-dispatch-software' },
  { title: 'The ROI of Fence Crew and Dispatch Software: What an Extra Job a Week Is Worth', description: 'See the real ROI of fence crew and dispatch software: how tighter scheduling, routing, and billing in FenceBossPro can add an extra fence install every week.', href: '/blogs/roi-fence-crew-dispatch-software' },
  { title: 'Scaling From One to Five Fence Crews With Dispatch Software', description: 'FenceBossPro turns one fence crew into five with shared scheduling, dispatch and routing, line-item estimates, and customer texts&mdash;so growth never breaks your day.', href: '/blogs/scaling-from-one-to-five-fence-crews-dispatch-software' },
  { title: 'Setting Up Fence Crew and Dispatch Software in Your First Week', description: 'A practical first-week plan to set up fence crew and dispatch software: load crews, materials, estimates, and the Job Board so your installs route clean.', href: '/blogs/setting-up-fence-crew-dispatch-software-first-week' },
  { title: 'Staging Materials Before Dispatch So Crews Never Wait on Parts', description: 'How fence crew software ties posts, panels, and hardware to each job so materials are staged and loaded before dispatch, and crews never wait on parts.', href: '/blogs/staging-materials-before-dispatch-fence-crew-software' },
  { title: 'Rescheduling Rained-Out Fence Crews Without Losing the Whole Week', description: 'See how FenceBossPro reschedules rained-out fence crews fast&mdash;drag-and-drop the Job Board, re-dispatch crews, and text customers so a wet day stays one day.', href: '/blogs/weather-reschedule-fence-crew-dispatch-software' },
  { title: 'The Whiteboard Versus Fence Crew and Dispatch Software: Why Paper Falls Apart', description: 'Why the shop whiteboard fails fence crews and how dispatch software sends jobs, materials, and routes to the field without erasing a single line.', href: '/blogs/whiteboard-vs-fence-crew-dispatch-software' },
];

const silo4 = [
  { title: 'Billing Posts, Panels, and Hardware: Itemizing Materials on Fence Invoices', description: 'See how FenceBossPro itemizes fence posts, panels, pickets, rails, concrete, gates, and hardware on every invoice so you bill materials accurately.', href: '/blogs/billing-materials-and-parts-on-fence-invoices-software' },
  { title: 'Branded, Professional Fence Invoices: Why How You Bill Shapes Your Reputation', description: 'See how FenceBossPro turns line-item fence estimates into clean, branded invoices with card-on-file payments that build trust and get you paid faster.', href: '/blogs/branded-professional-fence-invoices-software' },
  { title: 'Card-on-File Payments: How Fence Software Gets You Paid the Day the Gate Hangs', description: 'Card-on-file payments in fence software let you bill the second the last gate hangs, charge saved cards in seconds, and stop chasing checks for good.', href: '/blogs/card-on-file-payments-fence-business-software' },
  { title: 'Change Orders Without Lost Revenue: Billing Mid-Project Fence Changes in Software', description: 'See how FenceBossPro turns mid-project fence change orders into signed, billable line items so added footage, gates, and upgrades never get installed for free.', href: '/blogs/change-order-billing-fence-jobs-software' },
  { title: 'Client and Property Profiles: Keeping a Clean Billing History for Every Fence Customer', description: 'See how FenceBossPro client and property profiles store every fence estimate, invoice, deposit, and payment so each customer has a clean billing history.', href: '/blogs/client-property-profiles-fence-billing-history-software' },
  { title: 'Commercial Fence Invoicing: Handling Net-30 Terms and PO Numbers in Software', description: 'See how FenceBossPro handles commercial fence invoicing with net-30 terms, PO numbers, itemized materials, and progress billing for GCs and property managers.', href: '/blogs/commercial-fence-invoicing-net-terms-software' },
  { title: 'Connecting Fence Invoicing to Job Costing: Knowing the Profit on Every Fence', description: 'See how FenceBossPro ties fence invoices to job costing so you know the true profit on every wood, vinyl, chain link, and aluminum fence job.', href: '/blogs/connecting-fence-invoicing-to-job-costing-software' },
  { title: 'A Daily Invoicing Routine for Fence Crews: Billing Jobs Before You Leave the Site', description: 'A simple end-of-day invoicing routine for fence crews using FenceBossPro to bill posts, panels, gates, and labor from the job site before they pack up.', href: '/blogs/daily-invoicing-routine-fence-crews-software' },
  { title: 'Collecting Deposits on Fence Jobs: How Software Locks In Cash Before the First Post', description: 'See how FenceBossPro collects fence-job deposits at signing with card-on-file payments, progress billing, and automatic invoices so cash lands first.', href: '/blogs/deposit-billing-fence-jobs-software' },
  { title: 'The Full Billing Workflow: From Deposit to Final Payment on a Fence Project', description: 'See how FenceBossPro runs the entire fence billing workflow &mdash; from signed estimate and deposit through progress billing to a card-on-file final payment.', href: '/blogs/deposit-to-final-payment-billing-workflow-fence-software' },
  { title: 'Fence Invoicing Software: The Complete Guide to Billing a Fence Business', description: 'A complete guide to fence invoicing software: turn line-item bids into invoices, collect deposits and progress billing, and take card-on-file payments.', href: '/blogs/fence-invoicing-software-complete-guide' },
  { title: 'Syncing Fence Invoicing With QuickBooks: One Clean Set of Billing Records', description: 'See how FenceBossPro syncs fence estimates, deposits, and final invoices with QuickBooks so your billing records match without double data entry.', href: '/blogs/fence-invoicing-software-quickbooks-sync-billing' },
  { title: 'The Final Invoice: Billing Cleanly After the Fence Walkthrough and Sign-Off', description: 'How FenceBossPro turns the final fence walkthrough into a clean, accurate invoice with materials, change orders, and card-on-file payments built in.', href: '/blogs/final-invoice-after-fence-install-walkthrough-software' },
  { title: 'Billing Gates and Add-Ons: Capturing Every Upsell on the Fence Invoice', description: 'See how FenceBossPro turns gates, hardware, and add-ons into separate line items so no fence upsell ever slips off the final invoice.', href: '/blogs/gate-and-add-on-billing-fence-invoicing-software' },
  { title: 'Tracking Invoice Status: A Receivables Dashboard Built for Fence Contractors', description: 'See how FenceBossPro gives fence contractors a live receivables dashboard to track invoice status, deposits, and overdue balances so nothing slips.', href: '/blogs/invoice-status-tracking-fence-receivables-dashboard' },
  { title: 'Invoicing Straight From the Job Board: Closing the Loop on Completed Fence Jobs', description: 'See how FenceBossPro lets crews mark a fence job done and invoice straight from the Job Board, with card-on-file payment in minutes.', href: '/blogs/invoicing-from-the-job-board-fence-software' },
  { title: 'Linear-Foot Takeoffs to Invoice Line Items: Billing Fence Jobs by the Numbers', description: 'See how fence software turns linear-foot takeoffs into line-item estimates and clean invoices, so every post, panel, and gate gets billed accurately.', href: '/blogs/linear-foot-takeoffs-to-invoice-line-items-fence-software' },
  { title: 'Handwritten Invoices vs. Fence Billing Software: What Owners Gain by Switching', description: 'See what fence owners gain by trading handwritten invoices for FenceBossPro: faster billing, card-on-file payments, accurate material line items, and fewer errors.', href: '/blogs/manual-invoicing-vs-fence-billing-software' },
  { title: 'Giving Fence Customers Online Payment Options That Actually Get Used', description: 'See how FenceBossPro adds payment links, card-on-file, deposits, and progress billing to fence invoices so customers pay online fast &mdash; without the chase.', href: '/blogs/online-payment-options-fence-customers-software' },
  { title: 'Partial Payments and Payment Plans: Flexible Fence Billing That Still Gets You Paid', description: 'How fence invoicing software handles deposits, progress billing, and payment plans so you stay funded on big jobs without losing track of the balance.', href: '/blogs/partial-payments-payment-plans-fence-invoicing-software' },
  { title: 'Progress Billing for Large Fence Projects: Invoicing by Phase Without Losing Track', description: 'Bill big fence jobs in phases without losing track. See how FenceBossPro ties progress invoices to project milestones, deposits, and card-on-file payments.', href: '/blogs/progress-billing-large-fence-projects-software' },
  { title: 'Recurring Invoices for Fence Repair and Maintenance Accounts', description: 'Set up recurring invoices in FenceBossPro for fence repair and maintenance accounts so post resets, gate tune-ups, and inspections bill themselves on schedule.', href: '/blogs/recurring-invoicing-fence-repair-maintenance-software' },
  { title: 'Cutting Billing Errors on Fence Jobs: How Software Stops Costly Invoice Mistakes', description: 'See how FenceBossPro pulls invoices straight from your accepted fence estimate so posts, panels, gates, and labor bill right the first time.', href: '/blogs/reducing-billing-errors-fence-invoicing-software' },
  { title: 'Chasing Unpaid Fence Invoices: How Automated Reminders Shrink Your Receivables', description: 'See how FenceBossPro automated invoice reminders and texts collect overdue fence balances, cut your receivables, and stop the manual chase for unpaid jobs.', href: '/blogs/reducing-unpaid-fence-invoices-automated-reminders' },
  { title: 'The ROI of Fence Invoicing Software: What Faster Payments Are Worth to Your Crew', description: 'See the real ROI of fence invoicing software: faster deposits, card-on-file payments, fewer unpaid jobs, and more cash to keep your crew building.', href: '/blogs/roi-of-fence-invoicing-software-faster-payments' },
  { title: 'Sales Tax on Fence Invoices: Letting Software Calculate It Right Every Time', description: 'How FenceBossPro applies the correct sales tax rate to materials and labor on every fence invoice automatically, so your billing stays accurate.', href: '/blogs/sales-tax-on-fence-invoices-software' },
  { title: 'Scaling Fence Billing Across Multiple Crews Without Drowning the Office', description: 'How FenceBossPro turns multi-crew fence jobs into clean invoices, deposits, and card-on-file payments so your office bills faster without falling behind.', href: '/blogs/scaling-fence-billing-across-multiple-crews-software' },
  { title: 'Setting Up Fence Invoicing Software for the First Time: A Step-by-Step Walkthrough', description: 'A first-time setup walkthrough for fence invoicing software: import customers, build a materials catalog, configure deposits and progress billing, and turn on payments.', href: '/blogs/setting-up-fence-invoicing-software-first-time' },
  { title: 'Text-to-Pay Fence Invoices: A Customer Experience That Gets You Paid Faster', description: 'See how FenceBossPro texts fence invoices with a pay link so customers tap and pay from the driveway, getting your jobs paid faster with less chasing.', href: '/blogs/text-to-pay-fence-invoices-customer-experience' },
  { title: 'From Bid to Bill: Turning Line-Item Fence Estimates Into Invoices in One Click', description: 'See how FenceBossPro turns a line-item fence estimate into a finished invoice in one click, carrying every post, panel, and gate straight to the bill.', href: '/blogs/turning-fence-estimates-into-invoices-one-click' },
];

const silo5 = [
  { title: 'How to Cut No-Shows and Confusion With Automated Fence Appointment Reminders', description: 'See how FenceBossPro automated appointment reminders cut no-shows, confirm fence estimates and install dates, and keep crews from rolling to empty yards.', href: '/blogs/automated-fence-appointment-reminders' },
  { title: 'How to Build Accurate Line-Item Fence Estimates in Minutes Instead of Hours', description: 'See how FenceBossPro turns linear-foot takeoffs into priced, line-item fence estimates in minutes&mdash;posts, panels, rails, gates, and labor included.', href: '/blogs/build-line-item-fence-estimates-fast' },
  { title: 'How to Take Card-on-File Payments for Fence Jobs and Stop Chasing Final Checks', description: 'Use FenceBossPro to save a card on file, charge deposits, and auto-collect the final fence balance so you stop chasing checks after the gate swings.', href: '/blogs/card-on-file-payments-fence-jobs' },
  { title: 'How to Collect a Deposit Before You Order Fence Materials', description: 'Use FenceBossPro to collect a deposit and card-on-file payment before ordering posts, panels, and gates so material costs never come out of your pocket.', href: '/blogs/collect-deposit-before-ordering-fence-materials' },
  { title: 'How to Send Customer Texts at Every Stage of a Fence Project', description: 'Use FenceBossPro to send automatic customer texts at every fence project stage&mdash;from deposit to final walkthrough&mdash;so clients always know what is next.', href: '/blogs/customer-texts-fence-project-stages' },
  { title: 'How to Dispatch and Route Fence Crews So They Hit More Jobs Per Day', description: 'See how FenceBossPro dispatch and routing pack more fence installs and repairs into every crew day with smart scheduling, maps, and live crew texts.', href: '/blogs/dispatch-route-fence-crews' },
  { title: 'How Fence Business Software Pays for Itself in the First Month', description: 'See how fence business software pays for itself in month one through faster bids, accurate material takeoffs, on-time invoicing, and card-on-file payments.', href: '/blogs/fence-business-software-roi-first-month' },
  { title: 'How to Build a Fence Materials List From an Estimate So Nothing Gets Forgotten on Install Day', description: 'See how FenceBossPro turns a line-item fence estimate into a complete materials list so posts, panels, gates, and hardware are never forgotten.', href: '/blogs/fence-materials-list-from-estimate' },
  { title: 'Fence Business Software vs. Generic Field Service Tools: What Fencing Needs That They Miss', description: 'Generic field service tools miss what fencing needs. See how FenceBossPro handles linear-foot bids, materials, deposits, and multi-day fence installs.', href: '/blogs/fence-software-vs-generic-field-service' },
  { title: 'Fence Business Software vs. Spreadsheets: Where Spreadsheets Break Down', description: 'See exactly where spreadsheets fail a growing fence company and how FenceBossPro handles estimates, materials, scheduling, dispatch, and getting paid.', href: '/blogs/fence-software-vs-spreadsheets' },
  { title: 'How to Invoice a Fence Job the Day the Crew Finishes', description: 'How FenceBossPro turns a finished fence job into a sent invoice the same day &mdash; pulling line items, materials, deposits, and card payments from the original bid.', href: '/blogs/invoice-fence-job-day-crew-finishes' },
  { title: 'How to Manage Multiple Fence Crews From One Schedule', description: 'See how FenceBossPro lets you run multiple fence crews from one schedule and Job Board so installs, repairs, and gate jobs all stay on track.', href: '/blogs/manage-multiple-fence-crews-one-schedule' },
  { title: 'How to Manage Ornamental and Aluminum Fence Projects With Detailed Material Specs', description: 'Manage ornamental and aluminum fence projects with detailed material specs: line-item bids, panel and post takeoffs, gate hardware, crew scheduling, and billing.', href: '/blogs/manage-ornamental-aluminum-fence-projects' },
  { title: 'From Paper Bids to Software: How to Move Your Fence Company Off the Clipboard', description: 'FenceBossPro turns handwritten fence bids into line-item estimates with materials, takeoffs, deposits, scheduling, and card payments &mdash; no more clipboards.', href: '/blogs/move-fence-company-off-paper-bids' },
  { title: 'How to Price Wood, Vinyl, Chain Link, and Aluminum Fence by the Linear Foot', description: 'Build per-linear-foot rate tables by material in FenceBossPro so any estimator can turn a fence takeoff into a line-item bid in minutes.', href: '/blogs/price-fence-by-linear-foot-by-material' },
  { title: 'How to Set Up Progress Billing for Large Fence Installs', description: 'Set up progress billing for big fence installs in FenceBossPro so each milestone draw fires off the schedule against a card on file as the work gets done.', href: '/blogs/progress-billing-large-fence-installs' },
  { title: 'How to Store Property Profiles, Gate Locations, and Site Notes for Every Fence Job', description: 'How FenceBossPro stores property profiles, gate locations, and site notes so every crew shows up to a fence job knowing the layout, access, and what to build.', href: '/blogs/property-profiles-site-notes-fence-jobs' },
  { title: 'How to Quote Gates and Gate Hardware as Line Items on a Fence Estimate', description: 'Learn how FenceBossPro quotes gates and gate hardware as clean line items so hinges, latches, posts, and footings never fall off a fence estimate.', href: '/blogs/quote-gates-hardware-fence-estimate' },
  { title: 'How to Quote and Schedule Chain Link Fence Jobs Without Underbidding the Materials', description: 'Use FenceBossPro to build linear-foot chain link estimates that count every post, rail, and fitting, then drop the job straight onto the schedule.', href: '/blogs/quote-schedule-chain-link-fence-jobs' },
  { title: 'How to Run Your Entire Fence Business From One Platform: Estimates, Materials, Scheduling, and Payments', description: 'Run your whole fence business in one platform: line-item estimates, material takeoffs, crew scheduling, dispatch, invoicing, and card-on-file payments.', href: '/blogs/run-fence-business-one-platform' },
  { title: 'How to Run Your Fence Jobs From a Job Board Instead of a Whiteboard', description: 'Trade the dry-erase whiteboard for a live job board that turns fence bids into dispatched, materials-ready, billable jobs your crews can actually follow.', href: '/blogs/run-fence-jobs-from-job-board' },
  { title: 'How to Scale a Fence Business From Owner-Operator to Multiple Crews', description: 'Scale a fence company from owner-operator to multiple crews with software that handles estimates, materials, scheduling, dispatch, and invoicing.', href: '/blogs/scale-fence-business-owner-operator-to-crews' },
  { title: 'How to Schedule Fence Installs Around Material Lead Times and Crew Availability', description: 'Use FenceBossPro to schedule fence installs around post, panel, and gate lead times plus crew availability so your job board never stalls.', href: '/blogs/schedule-fence-installs-material-lead-times' },
  { title: 'How to Keep Fence Repair Calls From Blowing Up Your Install Schedule', description: 'Use FenceBossPro to slot fence repair calls into your install schedule with the Job Board, crew dispatch, and routing&mdash;without wrecking your big projects.', href: '/blogs/schedule-fence-repair-calls-around-installs' },
  { title: 'How to Set Up Your Fence Business in FenceBossPro: Clients, Properties, and the Job Board', description: 'Set up clients, properties, and the Job Board in FenceBossPro so your fence company quotes, schedules, and invoices every job from one place.', href: '/blogs/set-up-fence-business-software-clients-properties' },
  { title: 'How to Track Every Fence Job From Estimate to Final Payment', description: 'See how FenceBossPro tracks every fence job from line-item estimate through materials, scheduling, deposits, and final card-on-file payment.', href: '/blogs/track-fence-job-estimate-to-payment' },
  { title: 'How to Track Posts, Panels, Pickets, Rails, and Concrete on Every Fence Bid', description: 'See how FenceBossPro tracks posts, panels, pickets, rails, and concrete on every fence bid so your line-item estimates and material orders always match.', href: '/blogs/track-fence-materials-posts-panels-pickets' },
  { title: 'What Is Fence Business Software and When Your Fence Company Actually Needs It', description: 'Fence business software turns linear-foot takeoffs, material lists, bids, scheduling, and payments into one system. Here is what it is and when you need it.', href: '/blogs/what-is-fence-business-software' },
  { title: 'How to Win More Fence Bids With Fast, Professional Estimates', description: 'See how FenceBossPro helps fence contractors send fast, accurate line-item estimates with materials, posts, and gates priced right to win more bids.', href: '/blogs/win-more-fence-bids-professional-estimates' },
];

const silo6 = [
  { title: 'Estimating Aluminum and Ornamental Fence Jobs Without the Guesswork', description: 'See how FenceBossPro builds accurate aluminum and ornamental fence estimates&mdash;panels, posts, gates, and hardware priced from a linear-foot takeoff.', href: '/blogs/aluminum-ornamental-fence-estimates-software' },
  { title: 'What the Best Fence Contractor Software Does That Generic Tools Don&apos;t', description: 'Generic invoicing apps and spreadsheets miss linear-foot takeoffs, post-and-panel material lists, and progress billing. Here is what fence software adds.', href: '/blogs/best-fence-contractor-software-vs-generic' },
  { title: 'Chain Link Fence Takeoffs and Material Counts the Software Does for You', description: 'FenceBossPro turns chain link measurements into instant linear-foot takeoffs, full material counts, and a priced bid so you never miscount posts again.', href: '/blogs/chain-link-fence-takeoffs-software' },
  { title: 'Tracking Post-Setting and Concrete on Multi-Day Fence Jobs', description: 'See how FenceBossPro tracks post-setting, concrete cure days, and material across multi-day fence jobs with the Job Board, dispatch, and progress billing.', href: '/blogs/concrete-post-setting-job-tracking-software' },
  { title: 'Following Up on Open Fence Bids So Estimates Don&apos;t Go Cold', description: 'See how FenceBossPro tracks open fence bids, sends automatic follow-up texts, and turns cold estimates into signed jobs before they slip away.', href: '/blogs/fence-bid-follow-up-software' },
  { title: 'Handling Fence Change Orders Without Losing the Money', description: 'Capture fence change orders in FenceBossPro with line-item estimates, material adds, signed approvals, and progress billing so you never eat the extra cost.', href: '/blogs/fence-contractor-software-change-orders' },
  { title: 'The Customer Experience That Wins Fence Jobs: From Bid to Final Walk', description: 'See how FenceBossPro turns every step &mdash; line-item bids, deposits, scheduling, and texts &mdash; into a customer experience that wins more fence jobs.', href: '/blogs/fence-contractor-software-customer-experience' },
  { title: 'Keeping Fence Customers Updated With Automatic Job Texts', description: 'See how FenceBossPro automatic job texts keep fence customers updated from estimate to install to final invoice, without your office making a single call.', href: '/blogs/fence-contractor-software-customer-texts' },
  { title: 'Deposits and Progress Billing for Fence Jobs the Software Handles', description: 'See how FenceBossPro collects fence deposits, bills progress payments, and keeps card-on-file invoicing tied to every line-item estimate and material order.', href: '/blogs/fence-contractor-software-deposits-progress-billing' },
  { title: 'Invoicing and Card-on-File Payments for Fence Contractors', description: 'How FenceBossPro turns approved fence bids into clean invoices and collects faster with card-on-file payments, deposits, and automatic customer text reminders.', href: '/blogs/fence-contractor-software-invoicing-card-on-file' },
  { title: 'Running a Fence Company Without a Full-Time Office Manager', description: 'How fence contractor software handles estimates, scheduling, dispatch, and invoicing so a fence company can run lean without a full-time office manager.', href: '/blogs/fence-contractor-software-no-office-manager' },
  { title: 'The ROI of Fence Contractor Software: Where the Money Comes Back', description: 'See where fence contractor software pays for itself: faster line-item bids, tighter material takeoffs, full crews, and deposits and card-on-file payments.', href: '/blogs/fence-contractor-software-roi' },
  { title: 'Fence Contractor Software vs. Spreadsheets: Running Bids and Jobs the Hard Way', description: 'See why spreadsheets break down on fence bids, materials, and scheduling &mdash; and how fence contractor software runs estimates, jobs, and payments in one place.', href: '/blogs/fence-contractor-software-vs-spreadsheets' },
  { title: 'Giving Fence Crews a Mobile App for the Job Site', description: 'See how a fence crew mobile app puts estimates, materials lists, schedules, and dispatch in your installers&apos; pockets so jobs run on time.', href: '/blogs/fence-crew-mobile-app-field-software' },
  { title: 'From Fence Estimate to Paid Invoice in One System', description: 'See how FenceBossPro carries a fence job from line-item estimate to scheduled install to paid invoice in one connected system &mdash; no retyping, no gaps.', href: '/blogs/fence-estimate-to-invoice-software' },
  { title: 'Using the Job Board to Run Your Fence Shop Every Morning', description: 'Start every fence shop morning on the FenceBossPro job board: see crews, materials, installs, repairs, and gate jobs on one screen and dispatch in minutes.', href: '/blogs/fence-job-board-software-daily-use' },
  { title: 'Setting Material Markup and Margins on Every Fence Bid', description: 'See how fence contractor software applies consistent material markup and target margins to every bid so posts, panels, and gates always turn a profit.', href: '/blogs/fence-material-cost-markup-software' },
  { title: 'Managing Fence Repair Calls Between Your Big Install Jobs', description: 'How fence contractor software slots repair and gate calls between big installs&mdash;fast estimates, parts tracking, dispatch, the Job Board, and card-on-file pay.', href: '/blogs/fence-repair-jobs-software-scheduling' },
  { title: 'Quoting and Scheduling Gate Builds With Fence Software', description: 'See how fence software quotes custom gate builds line by line, tracks posts and hardware, and schedules the crew so every gate ships on time.', href: '/blogs/gate-jobs-quotes-fence-software' },
  { title: 'Building Line-Item Fence Estimates That Win the Bid', description: 'See how FenceBossPro builds clear line-item fence estimates with materials, labor, and gates so you bid faster, price right, and win more jobs.', href: '/blogs/line-item-fence-estimates-software' },
  { title: 'Linear-Foot Takeoffs Made Fast With Fence Contractor Software', description: 'See how FenceBossPro turns linear-foot takeoffs into fast, accurate fence bids by auto-counting posts, panels, rails, concrete, and gate hardware.', href: '/blogs/linear-foot-takeoffs-fence-contractor-software' },
  { title: 'Setting Up Your Fence Contractor Software in the First Week', description: 'A practical first-week setup plan for fence contractor software: load materials, build estimate templates, import clients, and start scheduling jobs fast.', href: '/blogs/setting-up-fence-contractor-software-first-week' },
  { title: 'Building Accurate Vinyl Fence Bids in Fence Contractor Software', description: 'How fence contractor software builds accurate vinyl fence bids from linear-foot takeoffs, post and panel counts, gate hardware, and concrete &mdash; line by line.', href: '/blogs/vinyl-fence-estimates-software' },
  { title: 'What Is Fence Contractor Software, and What Should It Actually Do?', description: 'Fence contractor software runs estimates, materials takeoffs, scheduling, dispatch, invoicing, and deposits so your fence crew closes jobs and gets paid faster.', href: '/blogs/what-is-fence-contractor-software' },
  { title: 'Faster Wood Fence Estimates: Pickets, Rails, and Posts by the Foot', description: 'See how FenceBossPro turns wood fence footage into a line-item estimate &mdash; pickets, rails, posts, and concrete counted by the foot in seconds.', href: '/blogs/wood-fence-estimates-software' },
];

const silo7 = [
  { title: 'Aluminum and Ornamental Fence Bidding Software: Sections, Posts, and Custom Runs', description: 'How FenceBossPro bids aluminum and ornamental fence by section and post, handles custom-cut runs, racked panels, and gate hardware on one clean line-item estimate.', href: '/blogs/aluminum-ornamental-fence-bidding-software' },
  { title: 'Card-on-File Payments for Fence Contractors: Get Paid the Day the Gate Closes', description: 'How card-on-file payments let fence contractors collect deposits, progress draws, and final balances automatically &mdash; no chasing checks after install.', href: '/blogs/card-on-file-payments-fence-contractors' },
  { title: 'Chain Link Fence Estimating Software: Linear Feet, Terminal Posts, and Fabric', description: 'See how FenceBossPro builds chain link fence estimates from linear-foot takeoffs, counting terminal posts, line posts, fabric, and gate hardware automatically.', href: '/blogs/chain-link-fence-estimating-software' },
  { title: 'Client and Property Profiles: How Fence Software Remembers Every Yard You Touch', description: 'See how FenceBossPro client and property profiles store every gate, post layout, and linear-foot run so your fence crews bid and build faster.', href: '/blogs/client-property-profiles-fence-software' },
  { title: 'Concrete and Post-Setting Takeoffs: How Fence Software Sizes Materials by the Hole', description: 'See how FenceBossPro turns linear-foot takeoffs into exact post, concrete, and hardware counts so your fence bids price every hole right.', href: '/blogs/concrete-post-setting-takeoffs-fence-software' },
  { title: 'Automated Customer Texts: Keeping Fence Clients in the Loop From Bid to Build', description: 'See how FenceBossPro automated customer texts keep fence clients updated from bid to build &mdash; deposits, scheduling, crew arrival, and final invoices.', href: '/blogs/customer-text-updates-fence-installation' },
  { title: 'Deposits and Progress Billing: How Fence Software Keeps Cash Flowing on Big Jobs', description: 'See how FenceBossPro deposits, progress billing, and card-on-file payments keep cash flowing on big fence installs from estimate to final invoice.', href: '/blogs/deposits-progress-billing-fence-jobs' },
  { title: 'Dispatch and Route Your Fence Crews Without the Morning Chaos', description: 'How FenceBossPro dispatches each fence crew a complete route, job scope, materials list, and gate notes in one action — no morning phone calls.', href: '/blogs/dispatch-fence-crews-routing-software' },
  { title: 'From Accepted Estimate to Scheduled Job: How Fence Software Closes the Gap', description: 'See how fence installation software turns an accepted estimate into a scheduled, dispatched job with deposits, materials, and crew assignments handled automatically.', href: '/blogs/fence-estimate-to-scheduled-job-software' },
  { title: 'In the Field: How Crews Use Fence Software on Their Phones at the Job Site', description: 'See how fence crews use FenceBossPro on their phones at the job site&mdash;pulling up the material list, marking jobs done, and texting customers from the truck.', href: '/blogs/fence-installation-crew-mobile-app' },
  { title: 'Fence Installation Software: The Complete Guide for Fence Contractors', description: 'A complete guide to fence installation software&mdash;line-item estimates, materials takeoffs, scheduling, dispatch, invoicing, and card-on-file payments.', href: '/blogs/fence-installation-software-complete-guide' },
  { title: 'Invoicing for Fence Contractors: Turn a Finished Run Into a Paid Invoice in Minutes', description: 'See how FenceBossPro turns an approved fence bid into an itemized invoice with deposits, progress billing, and card-on-file payments in minutes.', href: '/blogs/fence-installation-software-invoicing' },
  { title: 'The ROI of Fence Installation Software: What It Returns in the First 90 Days', description: 'See how fence installation software pays for itself in 90 days through faster bids, tighter material takeoffs, fewer dead miles, and quicker payments.', href: '/blogs/fence-installation-software-roi' },
  { title: 'Fence Installation Software vs Spreadsheets: Why Fence Crews Outgrow Excel', description: 'Why fence contractors outgrow spreadsheets&mdash;and how FenceBossPro replaces Excel with line-item bids, takeoffs, scheduling, and card-on-file invoicing.', href: '/blogs/fence-installation-software-vs-spreadsheets' },
  { title: 'The Job Board: How Fence Software Gives Every Crew the Day at a Glance', description: 'How the Job Board in fence installation software shows every crew their installs, repairs, and gate jobs for the day with materials, notes, and stops in order.', href: '/blogs/fence-job-board-software' },
  { title: 'From Posts to Hardware: How Fence Software Builds the Materials List for Every Job', description: 'See how FenceBossPro turns your fence estimate into a complete materials and parts list &mdash; posts, panels, rails, concrete, gates, and hardware &mdash; on every job.', href: '/blogs/fence-materials-parts-list-software' },
  { title: 'Fence Repair Software: Managing Small Jobs, Service Calls, and Quick Estimates', description: 'How fence repair software handles small service calls&mdash;quick line-item estimates, parts tracking, the Job Board, crew dispatch, and card-on-file payments.', href: '/blogs/fence-repair-job-management-software' },
  { title: 'Gates and Hardware: How Fence Software Stops the Parts From Falling Through the Cracks', description: 'Hinges, latches, and gate kits sink fence jobs when they are forgotten. See how FenceBossPro tracks every part from estimate to install.', href: '/blogs/gate-hardware-tracking-fence-software' },
  { title: 'How Fence Installation Software Builds Line-Item Estimates That Win More Bids', description: 'See how fence installation software builds detailed line-item estimates from linear-foot takeoffs, materials, and labor so you bid faster and close more jobs.', href: '/blogs/line-item-fence-estimates-that-win-bids' },
  { title: 'Linear-Foot Fence Takeoffs: How Software Turns Measurements Into Accurate Bids', description: 'See how fence software turns linear-foot takeoffs into accurate, line-item bids by auto-counting posts, panels, pickets, rails, concrete, and gate hardware.', href: '/blogs/linear-foot-fence-takeoffs-software' },
  { title: 'Managing a Full Fence Installation Backlog Without Losing Jobs', description: 'See how fence installation software keeps a packed backlog organized with the Job Board, scheduling, deposits, and customer texts so no signed job slips away.', href: '/blogs/manage-fence-installation-backlog-software' },
  { title: 'Manual Bidding vs Fence Software: Where Hand-Written Quotes Cost You Money', description: 'See where hand-written fence quotes leak profit and how software bids with linear-foot takeoffs, live material costs, and instant deposits win the job.', href: '/blogs/manual-vs-software-fence-bidding' },
  { title: 'Faster Bids, More Closed Jobs: Cutting Fence Estimate Turnaround With Software', description: 'See how fence estimating software cuts bid turnaround from days to minutes with line-item takeoffs, saved materials, and instant customer texts.', href: '/blogs/reduce-fence-bid-turnaround-time-software' },
  { title: 'Scaling From One Truck to Multiple Crews With Fence Installation Software', description: 'See how fence installation software lets you run multiple crews with a shared Job Board, crew dispatch, line-item bids, materials tracking, and invoicing.', href: '/blogs/scale-fence-business-multiple-crews-software' },
  { title: 'How Fence Installation Software Schedules Jobs Around Crews, Weather, and Material Lead Times', description: 'See how FenceBossPro schedules fence installs around crew availability, weather delays, and post, panel, and gate lead times so your job board keeps moving.', href: '/blogs/schedule-fence-installation-jobs-software' },
  { title: 'Setting Up Fence Installation Software: Your First Week Step by Step', description: 'A day-by-day first-week plan for setting up fence installation software: import customers, build material lists, send estimates, and schedule crews.', href: '/blogs/set-up-fence-installation-software-first-week' },
  { title: 'Tracking Material Costs and Job Profitability on Every Fence Project', description: 'See how FenceBossPro ties posts, panels, and gate hardware to each bid so you know the real profit on every fence job before you cash the check.', href: '/blogs/track-fence-materials-cost-job-profitability' },
  { title: 'Vinyl Fence Installation Software: Quoting Panels and Sections Without Guesswork', description: 'FenceBossPro turns linear-foot vinyl fence takeoffs into accurate panel-and-post estimates, then carries the same numbers into scheduling, dispatch, and invoicing.', href: '/blogs/vinyl-fence-installation-software' },
  { title: 'What to Look For in Fence Installation Software: A Buyer Checklist for Contractors', description: 'A practical buyer checklist for fence installation software: line-item bids, material takeoffs, scheduling, dispatch, invoicing, and card-on-file payments.', href: '/blogs/what-to-look-for-fence-installation-software' },
  { title: 'Wood Fence Estimating Software: Pricing Pickets, Rails, and Posts the Right Way', description: 'See how FenceBossPro builds wood fence estimates from a linear-foot takeoff, pricing every picket, rail, post, and bag of concrete so your bids actually hold margin.', href: '/blogs/wood-fence-estimating-software' },
];

export default function BlogIndexPage() {
  return (
    <BlogShell>
      <div className="blog-index">
        <h1>Fence Business Software Blog</h1>
        <p className="blog-index-sub">Guides on estimating, scheduling, crew dispatch, materials, invoicing, and growing a fence company.</p>

        <h2 className="blog-index-silo-title">Fencing Software</h2>
        <div className="blog-index-grid">
          {silo0.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Estimating Software</h2>
        <div className="blog-index-grid">
          {silo1.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Scheduling Software</h2>
        <div className="blog-index-grid">
          {silo2.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Crew &amp; Dispatch Software</h2>
        <div className="blog-index-grid">
          {silo3.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Invoicing &amp; Billing</h2>
        <div className="blog-index-grid">
          {silo4.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Business Software</h2>
        <div className="blog-index-grid">
          {silo5.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Contractor Software</h2>
        <div className="blog-index-grid">
          {silo6.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>

        <h2 className="blog-index-silo-title">Fence Installation Software</h2>
        <div className="blog-index-grid">
          {silo7.map((post) => (
            <a key={post.href} href={post.href} className="blog-index-card"><h3>{post.title}</h3><p>{post.description}</p></a>
          ))}
        </div>
      </div>
    </BlogShell>
  );
}
